sudo: false
language: node_js
node_js: node
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
branches:
  only:
    - master
addons:
  sauce_connect: true
before_install:
  - npm install yarn -g
install:
  - yarn
script:
  - yarn run lint
  - yarn run test:sauce
  - yarn run test
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
notifications:
  email: change
